# Generated by Django 3.0.5 on 2020-05-02 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstN', models.TextField()),
                ('lastN', models.TextField()),
                ('city', models.TextField()),
                ('email', models.TextField()),
                ('image_url', models.URLField(blank=True)),
            ],
        ),
    ]
