# Generated by Django 3.0.5 on 2020-05-03 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_fb', '0002_statusmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.TextField(verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.TextField(verbose_name='Email Adress'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='firstN',
            field=models.TextField(verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image_url',
            field=models.URLField(blank=True, verbose_name='Image URL'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lastN',
            field=models.TextField(verbose_name='Last Name'),
        ),
    ]
