# Generated by Django 3.0.5 on 2020-05-03 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_fb', '0004_auto_20200503_0334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusmessage',
            name='timestamp',
            field=models.TimeField(),
        ),
    ]
