# Generated by Django 3.0.5 on 2020-05-03 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_fb', '0005_auto_20200503_0339'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusmessage',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
