# Generated by Django 3.0.5 on 2020-05-06 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='genre',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artist',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='hometown',
            field=models.TextField(default=None, verbose_name='Hometown'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artist',
            name='propic',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='song',
            name='name',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
